from .nodes.image import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .nodes.image import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.rembg import NODE_CLASS_MAPPINGS as REMBG_NODE_CLASS_MAPPINGS
from .nodes.rembg import NODE_DISPLAY_NAME_MAPPINGS as REMBG_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.color import NODE_CLASS_MAPPINGS as COLOR_NODE_CLASS_MAPPINGS
from .nodes.color import NODE_DISPLAY_NAME_MAPPINGS as COLOR_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.text_preview import NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS
from .nodes.text_preview import NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.shape_language import NODE_CLASS_MAPPINGS as SHAPE_NODE_CLASS_MAPPINGS
from .nodes.shape_language import NODE_DISPLAY_NAME_MAPPINGS as SHAPE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **IMAGE_NODE_CLASS_MAPPINGS,
    **REMBG_NODE_CLASS_MAPPINGS,
    **COLOR_NODE_CLASS_MAPPINGS,
    **TEXT_NODE_CLASS_MAPPINGS,
    **SHAPE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **REMBG_NODE_DISPLAY_NAME_MAPPINGS,
    **COLOR_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **SHAPE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
