from .nodes.image import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .nodes.image import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.rembg import NODE_CLASS_MAPPINGS as REMBG_NODE_CLASS_MAPPINGS
from .nodes.rembg import NODE_DISPLAY_NAME_MAPPINGS as REMBG_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.color import NODE_CLASS_MAPPINGS as COLOR_NODE_CLASS_MAPPINGS
from .nodes.color import NODE_DISPLAY_NAME_MAPPINGS as COLOR_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.text_preview import NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS
from .nodes.text_preview import NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.shape_language import NODE_CLASS_MAPPINGS as SHAPE_NODE_CLASS_MAPPINGS
from .nodes.shape_language import NODE_DISPLAY_NAME_MAPPINGS as SHAPE_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.draw_text import NODE_CLASS_MAPPINGS as DRAW_NODE_CLASS_MAPPINGS
from .nodes.draw_text import NODE_DISPLAY_NAME_MAPPINGS as DRAW_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.layout import NODE_CLASS_MAPPINGS as LAYOUT_NODE_CLASS_MAPPINGS
from .nodes.layout import NODE_DISPLAY_NAME_MAPPINGS as LAYOUT_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.poster_template_loader import NODE_CLASS_MAPPINGS as PTL_NODE_CLASS_MAPPINGS
from .nodes.poster_template_loader import NODE_DISPLAY_NAME_MAPPINGS as PTL_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.poster_mask_generator import NODE_CLASS_MAPPINGS as PMG_NODE_CLASS_MAPPINGS
from .nodes.poster_mask_generator import NODE_DISPLAY_NAME_MAPPINGS as PMG_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.poster_text_renderer import NODE_CLASS_MAPPINGS as PTR_NODE_CLASS_MAPPINGS
from .nodes.poster_text_renderer import NODE_DISPLAY_NAME_MAPPINGS as PTR_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.poster_logo_placer import NODE_CLASS_MAPPINGS as PLP_NODE_CLASS_MAPPINGS
from .nodes.poster_logo_placer import NODE_DISPLAY_NAME_MAPPINGS as PLP_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.poster_color_engine import NODE_CLASS_MAPPINGS as PCE_NODE_CLASS_MAPPINGS
from .nodes.poster_color_engine import NODE_DISPLAY_NAME_MAPPINGS as PCE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **IMAGE_NODE_CLASS_MAPPINGS,
    **REMBG_NODE_CLASS_MAPPINGS,
    **COLOR_NODE_CLASS_MAPPINGS,
    **TEXT_NODE_CLASS_MAPPINGS,
    **SHAPE_NODE_CLASS_MAPPINGS,
    **DRAW_NODE_CLASS_MAPPINGS,
    **LAYOUT_NODE_CLASS_MAPPINGS,
    **PTL_NODE_CLASS_MAPPINGS,
    **PMG_NODE_CLASS_MAPPINGS,
    **PTR_NODE_CLASS_MAPPINGS,
    **PLP_NODE_CLASS_MAPPINGS,
    **PCE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **REMBG_NODE_DISPLAY_NAME_MAPPINGS,
    **COLOR_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **SHAPE_NODE_DISPLAY_NAME_MAPPINGS,
    **DRAW_NODE_DISPLAY_NAME_MAPPINGS,
    **LAYOUT_NODE_DISPLAY_NAME_MAPPINGS,
    **PTL_NODE_DISPLAY_NAME_MAPPINGS,
    **PMG_NODE_DISPLAY_NAME_MAPPINGS,
    **PTR_NODE_DISPLAY_NAME_MAPPINGS,
    **PLP_NODE_DISPLAY_NAME_MAPPINGS,
    **PCE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
